services:
  - type: web
    name: vulnsight-ai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "120"
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: vulnsight_ai
      - key: ZAP_API_URL
        sync: false
      - key: ZAP_API_KEY
        sync: false
